{ nixpkgs }:

let
  release = import ./nixos/release-combined.nix { inherit nixpkgs; supportedSystems = ["armv7l-linux"]; };
  pkgs = import nixpkgs {};
in {
  #inherit (release.nixpkgs) linux_latest bastet systemd hello qemu libdrm;

  toUpload = pkgs.releaseTools.aggregate {
    name = "foo";
    constituents = map (x: x.armv7l-linux or null) (with release.nixpkgs; [
      acl
      alsaUtils
      asciidoc
      atftp
      attr
      audit
      autoconf
      automake
      bash
      bashCompletion
      bashInteractive
      bastet
      bc
      bcache-tools
      bind
      binutils
      bison
      blktrace
      bluez
      bonnie
      brotli
      btrfs-progs
      busybox
      bzip2
      cacert
      ccrypt
      cifs-utils
      cloog
      cloog_0_18_0
      cmake
      coreutils
      cpio
      cryptsetup
      cups
      curl
      cyrus_sasl
      dblatex
      dbus
      ddrescue
      dejavu_fonts
      dhcp
      dhcpcd
      diffutils
      dmraid
      docbook5
      docbook_xml_dtd_412
      docbook_xml_dtd_42
      docbook_xml_dtd_43
      docbook_xml_dtd_44
      docbook_xml_dtd_45
      docbook_xsl
      docbook_xsl_ns
      dosfstools
      doxygen
      dropbear
      dtc
      dtrx
      e2fsprogs
      efibootmgr
      efivar
      elfutils
      elinks
      emacs25-nox
      ethtool
      f2fs-tools
      file
      findutils
      fio
      fish
      flashbench
      flex
      fontconfig
      fontconfig_210
      fontconfig-penultimate
      fontconfig-ultimate
      freefont_ttf
      fuse
      fuse3
      gawk
      gdb
      getopt
      gettext
      gfortran
      giflib
      git
      gitFull
      gitMinimal
      glib
      glibc
      glibcLocales
      gmp4
      gmp5
      gmp6
      gmpxx
      gnome_doc_utils
      gnu-efi
      gnugrep
      gnum4
      gnused
      gnutar
      gperf
      gpm
      gptfdisk
      gtk_doc
      gzip
      hdparm
      host
      htop
      i2c-tools
      iana_etc
      iftop
      imlib2
      intltool
      iperf
      iproute
      iptables
      iputils
      isl
      isl_0_11
      isl_0_12
      isl_0_14
      isl_0_15
      iw
      jfsutils
      jq
      kexectools
      keyutils
      kmod
      kmod-blacklist-ubuntu
      kmod-debian-aliases
      less
      leveldb
      libaio
      libbsd
      libcap
      libcap_ng
      liberation_ttf
      libfaketime
      libgcrypt
      libgpgerror
      libiconv
      libmpc
      libpng
      libpng12
      libpng_apng
      libsigsegv
      libssh
      libssh2
      libtool
      libusb
      libusb1
      libuuid
      libxslt
      linuxHeaders
      lshw
      lsof
      lvm2
      lz4
      m4
      man
      mdadm
      memtester
      meson
      mkinitcpio-nfs-utils
      mmc-utils
      mosh
      most
      mpfr
      mssys
      mtools
      mtr
      musl
      nano
      ncdu
      ncurses
      netcat
      netcat-openbsd
      nethack
      nettools
      nfs-utils
      nghttp2
      nix
      nix1
      nix-bash-completions
      nix-info
      nix-prefetch-git
      nix-prefetch-svn
      nix-serve
      nixStable
      nixUnstable
      nmap
      nox
      nssTools
      ntp
      nukeReferences
      oniguruma
      openldap
      openresolv
      openssh
      openssl
      openssl_1_0_2
      openvpn
      pam
      parted
      patchutils
      paxctl
      pciutils
      pcre
      perl
      picocom
      pkgconfig
      pmutils
      polkit
      procps
      psmisc
      pulseaudioLight
      pv
      python2
      python3
      quota
      raspberrypifw
      raspberrypi-tools
      readline
      reiserfsprogs
      rfkill
      rng_tools
      rogue
      rsync
      ruby
      rxvt_unicode
      samba
      screen
      sdparm
      shadow
      sharutils
      smartmontools
      socat
      sox
      spidermonkey
      sqlite
      sshfs-fuse
      strace
      su
      subversion
      sudo
      systemd
      tcpdump
      testdisk
      texinfoInteractive
      time
      tmux
      trace-cmd
      traceroute
      tree
      tzdata
      ubootTools
      udisks
      udisks2
      unifont
      unzip
      usbutils
      utillinux
      utillinuxCurses
      vim
      vim_configurable
      vimHugeX
      w3m
      w3m-nox
      weechat
      wget
      which
      wirelesstools
      wpa_supplicant
      xfsprogs
      xlibsWrapper
      xmlto
      xz
      yasm
      zip
      zsh
    ]);
  };

  inherit (release) nixpkgs;

  #inherit (release.nixos) sd_image;
}
